---
title: "Schedule"
---

| **Week** |  **Date**   | **Lead Instructor**            |           **Topic**                                                          |                          **Functions introduced**                                                                             |         **Assigned**         |           **Due**       |       **Reading**                         |
| :------- | :---------: | :----------------------------: | :--------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------------------------------: | :--------------------------: | :---------------------: | :---------------------------------------: |
|     1a   |     3/30/20 |              Joe               |                    [Intro to course<br/>Installing software](slides/w1p1-intro/w1p1.pdf)                   |                                                                                                                               | Final <br/>Get to know data  |                         | [HML Ch. 1](https://bradleyboehmke.github.io/HOML/intro.html) |
|     1b   |     4/1/20  |             Daniel             |  [Inference vs. Prediction<br/>Estimating $f$<br/>Regression vs Classification](slides/w1p2-inf-v-pred.html)|                                                                                                |                              |                         | [APM: Ch. 1](https://canvas.uoregon.edu/files/8215106/download?download_frd=1)<br/>[ISLR: Ch. 2.1](https://canvas.uoregon.edu/files/8215162/download?download_frd=1)|
|     2a   |     4/6/20  |              Joe               |         [Bias-variance tradeoff<br/>test set<br/>k-fold CV (& repeats)](slides/w2p1-bias-variance-resampling/w2p1.pdf)        |  `initial_split`<br/>`train()`<br/>`test()`<br/>`vfold_cv()` & others                                                         |                              |                         | [ISLR: Ch. 2.2](https://canvas.uoregon.edu/files/8215189/download?download_frd=1)<br/>[ISLR: Ch 5.1](https://canvas.uoregon.edu/files/8216177/download?download_frd=1)|
|     2b   |     4/8/20  |              Joe               |  Lab 1: <br/>Resampling 							                                       |                                                                               	                                               |           [Lab 1](lab1.html)              |                         |                                           |
|     3a   |     4/13/20 |             Daniel             |                  [Variable Selection & <br/>Model performance](slides/w3p1-var-select-model-perf.html)                 |  Choose “model function”<br/>`set_engine()`<br/>`set_mode()`<br/>`fit_resamples()`<br/>`collect_metrics()`<br/>`select_best()`|                              |                         | [ISLR: Ch. 6.1](https://canvas.uoregon.edu/files/8216183/download?download_frd=1)<br/> [APM: Ch. 5](https://canvas.uoregon.edu/files/8215118/download?download_frd=1)<br/>[APM: Ch. 11](https://canvas.uoregon.edu/files/8216188/download?download_frd=1) |
|     3b   |     4/15/20 |             Daniel             |            [Lab 2: <br/>Building a predictive lm and Measuring performance](lab2.html)    |                                                                                                                        	     |           Lab 2              |      Lab 1              | [HML: Ch. 4](https://bradleyboehmke.github.io/HOML/linear-regression.html) <br/>[APM: Ch. 6.1 & 6.2](https://canvas.uoregon.edu/files/8215122/download?download_frd=1) |
|     4a   |     4/20/20 |              Joe               |                  [Extending lm: Ridge, Lasso, Elastic net](slides/w4p1-penalized-regression/w4p1.pdf)                     |  New arguments to `linear_reg()`<br/>`metric_set()`<br/>`tune_grid()`<br/>`grid_regular()`<br/>`show_best()`                  |                              |                         | [HML: Ch. 6](https://bradleyboehmke.github.io/HOML/regularized-regression.html) <br/>[APM: Ch. 6.4](https://canvas.uoregon.edu/files/8215128/download?download_frd=1) |
|     4b   |     4/22/20 |              Joe               |                         Lab 3:<br/>Penalized Regression                      |                                                                                                                             	 |           [Lab 3](lab3.Rmd)              |      Lab 2              |                                           |
|     5a   |     4/27/20 |             Daniel             |                              [Feature engineering](slides/w5p1-feature-engineering.html)                             |  [{recipes}](https://tidymodels.github.io/recipes/)                                                                           |                              |                         | [FE: Ch. 1](http://www.feat.engineering/intro-intro.html)<br/> [HML: Ch. 3](https://bradleyboehmke.github.io/HOML/engineering.html) |
|     5b   |     4/29/20 |             Daniel             |              Lab 4: <br/>Feature Engineering (Dimension Reduction)           |                                                                                                                               |           Lab 4              |Lab 3<br/>Preliminary Fit 1    |                                           |
|     6a   |     5/4/20  |              Joe               |                             [*K*-nearest neighbor](slides/w6p1-knn/w6p1.pdf)                             |       `nearest_neighbor()`<br/>`grid_max_entropy()`<br/>`autoplot()`                                                          |                              |                         | [HML: Ch. 8](https://bradleyboehmke.github.io/HOML/knn.html) |
|     6b   |     5/6/20  |              Joe               |                  Lab 5: <br/> *K*NN                                          |                                                                                                                               |           Lab 5              |      Lab 4                   |                                           |
|     7a   |     5/11/20 |             Daniel             |                                [Decision trees](slides/w7p1-decision-trees.html)                                |                                                                                                                               |                              |                         |[HML: Ch. 9](https://bradleyboehmke.github.io/HOML/DT.html) |
|     7b   |     5/13/20 |             Daniel             |                                 [Bagged trees](slides/w7p2-bagging.html)                                 |                                                                                                                               |                              |      Lab 5                   |[HML: Ch. 10](https://bradleyboehmke.github.io/HOML/bagging.html) |
|     8a   |     5/18/20 |              Joe               |                                [Random forests](slides/w8p1-random-forests/w8p1.pdf)                                |             `{workflows}`<br/>`extract()`                                                                                                                 |                              |                         |[HML: Ch. 11 ](https://bradleyboehmke.github.io/HOML/random-forest.html) |
|     8b   |     5/20/20 |           Joe/Daniel           |             Lab 6: <br/> Ensemble Methods                                    |                                                                                                                               |           Lab 6              |    Preliminary Fit 2    |                                           |
|     9a   |     5/25/20 |                                |                                   Memorial Day (no class)                    |                                                                                                                               |                              |                         |[HML Ch. 12](https://bradleyboehmke.github.io/HOML/gbm.html) |
|     9b   |     5/27/20 |             Daniel             |  [Boosted trees](slides/w9p2-boosted-trees.html)                             |                                                                                                                               |                              |      Lab 6              |                                           |
|     10a  |     6/1/20  |             Daniel             |                             [Advanced topics in ML](slides/w10p1-advanced-topics.html)                            |                                                                                                                               |                              |                         |                [HML Ch. 13](https://bradleyboehmke.github.io/HOML/deep-learning.html) & [15](https://bradleyboehmke.github.io/HOML/stacking.html) |
|     10b  |     6/3/20  | Guest Lecture: Sondra Stegenga |                                   [ML Ethics](slides/DataEthics_2020.pdf)                                  |                                                                                                                               |                              |                         |[Floridi & Taddeo (2016)](https://royalsocietypublishing.org/doi/full/10.1098/rsta.2016.0360) |
| Finals Week | 6/10/20  |                                |                                                                              |                                                                                                                               |                              | Final Project           |                                           |