---
title: "Syllabus"
output:
  html_document:
    toc: true
    toc_float: true
---

## EDLD 610: Applied Machine Learning for Educational Data Scientists (CRN: 37108; 3 credit hours)
* **Term:** Spring 2020
* **Time:** 12:00 - 1:20
* **Classroom:** Zoom
* **Instructors:** 
	* Joseph Nese, PhD
		- *email:* (preferred contact method) [jnese@uoregon.edu](mailto:jnese@uoregon.edu)
		- *phone:* 541-346-3535
		- *office:* 175 Lokey
		- *office hours*: By appointment
		- *pronouns:* he/him/his
	+ Daniel Anderson, PhD
		- *email:* (preferred contact method) [daniela@uoregon.edu](mailto:daniela@uoregon.edu)
		- *phone:* 541-346-3317
		- *office:* 175 Lokey
		- *office hours*: By appointment
		- *pronouns:* he/him/his

# Course Overview
This is the fourth course in a sequence of courses on educational data science (EDS), taught using free and open-source statistical programming languages. This course focuses on applied machine learning (ML), with an emphasis on supervised learning methods that have emerged over the last several decades. The primary goal of these methods is to create models capable of making accurate predictions, which generally implies less emphasis on statistical inference.

## Student Learning objectives
By the end of this course students will be able to
* Describe the framework of machine learning (i.e. supervised vs. unsupervised learning) and how it differs from standard inferential statistics.
* Discuss the bias-variance tradeoff in supervised learning and apply the concept in making decisions about model selection.
* Construct various supervised learning models, including linear regression (for prediction rather than inference), penalized regression (ridge/lasso), various decision tree models (including bagged and boosted trees, and random forests), and k-nearest neighbor models.
* Measure and contrast the performance of various models.
* Construct models for both classification- and regression-based problems. 
* Conduct feature engineering, including dimension reduction, to increase model performance (and quantify the degree to which model performance changed).


# Course Readings 
All course readings are freely available online or will be provided by the
instructor. 

## Books (required)
* Bohemke, B. & Greenwell, B. (2019). [Hands on Machine Learning with R](https://bradleyboehmke.github.io/HOML/). New York, NY: Taylor & Francis.
* James, Gareth et. al. (2017). [An Introduction to Statistical Learning with R](http://faculty.marshall.usc.edu/gareth-james/ISL/). New York, NY: Springer.
* Kuhn, M and Johnson, Kjell (2014). Applied Predictive Modeling in R, New York, NY: Springer.
* Kuhn M., & Johnson, K. (2019). [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering). New York, NY: Taylor & Francis.

## Books (not required, but possibly helpful)
* Efron, B. & Hastie, T. (2016). [Computer age statistical inference](http://web.stanford.edu/~hastie/CASI/). Cambridge, England: Cambridge University Press.
* Hastie, T., Tibshirani, R., & Friedman, J. (2009). [The elements of statistical learning: Data mining, inference, and prediction](https://web.stanford.edu/~hastie/ElemStatLearn/). New York, NY: Springer.
* Hadley Wickham & Garrett Grolemund, [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://r4ds.had.co.nz)

# Assignments and Grading
Your final grade will be composed of three components: 

* ~~Attendance: 20 points (10%; essentially one point per day)~~
* 6 labs at 11 or 12 points each (70 points; 35%) 
* Final Project (130 points; 65%)
  + Preliminary fit 1 (10 points)
  + Preliminary fit 2 (10 points)
  + Blog post (110 points)
  	* Data description (30 points)
  	* Model fit description (35 points)
  	* Model fits (25 points)
  	* Data visualization (10 points)
  	* Reproducibility (10 points)

Note - up to 5 points extra credit will be awarded to the team providing the most performant model

## ~~Attendance (20 points)~~
~~A critical component of learning data science includes receiving structured feedback as you problem-solve coding and data issues. Each lab will be introduced and begun in class, so that as a group we can talk through the task at hand. Supporting your classmates is also important, and so attendance during final presentations is mandatory.~~

## Labs (70 points; 35%)
There are 6 labs during the course. All labs will be scored on a “best honest effort” basis, which generally implies zero or full credit (i.e., the assignment was or was not fully completed). However, labs may require students complete specific portions before moving on to the next sections. If you find yourself stuck and unable to proceed, **please contact the instructor for help rather than submitting incomplete work**. Contacting the instructor is part of the “best honest effort”, and can result in full credit for an assignment even if the work is not fully complete. **If the assignment is not complete, and the student has not contacted the instructor for help or visited office hours, it is likely to result is a partial credit score or a zero**. Labs submitted late will be docked by 30% (3 points).

## Final Project (130 points; 65%)
The final project in this class is a group project to develop a predictive model for unseen data, along with a blog post describing your methods, including a description of the data used and the analysis procedure, along with an analysis of model performance and description of why you chose the model you did.

We will be using the [kaggle](https://www.kaggle.com) platform to host a local competition. You will receive a link to our class competition page the first week of class. As a team, you will need to work together to build a predictive model. You may link the data to outside data to help increase the performance of your model (e.g., [NCES](https://nces.ed.gov)). You will have access to the training dataset, which you will use to build, tune, and evaluate a predictive model. Once you have settled on a model, you will make predictions on a separate set of data that has all the same features (variables) except the outcome. You will then upload these predictions to kaggle, which will provide you with an estimate of your model accuracy on a portion of the test dataset (but not the full test data). Finally, at the end of the course, each team's most performant model will be evaluated against the full test data (note that this final test regularly leads to changes in the leader board ranking for real kaggle competitions). The team with the best model will be awarded five points extra credit.

### Preliminary fits (20 points)
At the end of Week 5 and Week 8 each team will be required to submit preliminary predictions. Note, you may submit predictions at any time, but you must submit your first predictions by Week 5, and predictions from a new model by Week 8. A quantitative indicator of prediction accuracy will automatically be provided. Submissions will be scored on an “all or nothing” basis at 10 points each. In other words, if your group provides a set of predictions, you will all receive credit, regardless of the performance of the model. 

### Blog post(s) (110 points)
The primary means by which you will be evaluated on the final project will be through a blog post, or set of blog posts. It is assumed that all students are comfortable creating blog posts, given the content covered in previous courses (specifically EDLD 652). Share relevant code within the blog post(s) to better describe your approach. The components and scoring of the blog post(s) are as follows:

#### Description of the data (30 points)
While all teams will work with the same data, the procedures you use with the data are likely to be different than those used by other teams. Describe core features of the data, any additional data you joined in and why, and basic descriptives. Note that this may be a relevant blog post on its own, or a major section within a single blog post.

The description should be sufficiently clear that the instructor understands all the variables that were included in your modeling, and how the final analytic dataset was constructed, without actually viewing your code. While specific code snippets can be included in this section to add clarity, the reader should not have to rely on this code to understand the data preparation. 

Provide a summary of the variables (e.g., how many categorical/continuous variables were included, what were the range of values, etc.), and any feature engineering applied to the data. If missing data are present, discuss how these values were handled, variable transformations, etc. Use this section to explain your data splitting process for model evaluation. 

#### Description of the models fit (35 points)
At least three models must be fit to the data. Describe each model fit, why the given model was selected, hyperparameters to be optimized, assumptions of the model, and a high-level (think broad audience) description of what the model is doing and why it is appropriate (even as an initial starting point). Discuss how you will evaluate model performance.

#### Model fits (25 points)
Describe your model fitting procedure(s) and the results of your model evaluation. Compare and contrast the different fits, including a discussion of model performance. Share code to communicate your procedures, and discuss your final model selection and the evidence that led you to this selection.

You will also need to submit your final model predictions from your final model so that a quantitative indicator of prediction accuracy can be provided.

#### Data visualization (10 points)
Include at least two plots (you may include more) to help communicate your findings. The plots may be of initial data explorations, fits of individual models, and/or plots displaying competing model performance. 

#### Reproducibility (10 points)
All code should be housed in a GitHub repository  and be fully reproducible. The only exception is if external data were used that are sufficiently large that they cannot be stored in the repository (without utilizing LFS). In that case, please make an empty “data” folder with a README file describing how interested parties can access the data. If possible, include a script that downloads the file and places it in the correct directory.

#### Extra credit (5 points)
Up to five points extra credit will be awarded to the team providing the most performant model. If there are ties amongst teams, extra credit will be awarded at the discretion of the instructor.

# Grading Components (200 points possible)
|  **Lower percent** |**Lower point range**  | **Grade** | **Upper point range**  | **Upper percent**|
|  :------: | :------   | :-:| :-------: | ----:|
|  0.97     | (194 pts) | A+ |           |      |
|  0.93     | (186 pts) | A  | (194 pts) | 0.97 |
|  0.90     | (180 pts) | A- | (186 pts) | 0.93 |
|  0.87     | (174 pts) | B+ | (180 pts) | 0.90 |
|  0.83     | (166 pts) | B  | (174 pts) | 0.87 |
|  0.80     | (160 pts) | B- | (166 pts) | 0.83 |
|  0.77     | (154 pts) | C+ | (160 pts) | 0.80 |
|  0.73     | (146 pts) | C  | (154 pts) | 0.77 |
|  0.70     | (140 pts) | C- | (146 pts) | 0.73 |
|           |           | F  | (140 pts) | 0.70 |

# Student Engagement Inventory
Graduate: 1 credit hour = 40 hours of student engagement (3 credit hours = 120 hours of student engagement) 

| **Educational activity** | **Hours student engaged** | **Explanatory comments (if any):**                                                                               |
| :----------------------- | :-----------------------: | :--------------------------------------------------------------------------------------------------------------- |
| Course attendance        |            26.5           | 20 meetings, at 80 minutes per meeting                                                                           |
| Assigned readings        |            26.5           | Weekly readings are assigned, and are expected to take roughly as long to complete as the in-seat time per week. |
| Projects                 |            30             | Final project, as described above (~15 hours on data prep, 10 hours on model fitting, 15 hours on blog post).    |
| Homework                 |            37             | 6 labs, at approximately 4.5 hours per lab spent out of class                                                    |
| Total hours:             |            120            |                                                                                                                  |
# Campus Emergency
In the event of a campus emergency that disrupts academic activities, course requirements, deadlines, and grading percentages are subject to change. Information about changes in this course will be communicated as soon as possible by email, and on Canvas. If we are not able to meet face-to-face, students should immediately log onto Canvas and read any announcements and/or access alternative assignments. Students are also encouraged to continue the readings and other assignments as outlined on this syllabus or subsequent syllabi.

# Attendance and Absence Guidelines
~~Attendance at all class and discussion groups is expected and required.~~

~~Students must contact the instructor in case of illness or emergencies that preclude attending class sessions. Messages can be left on the instructor's voice mail or e-mail at any time of the day or night, prior to class. If no prior arrangements have been made before class time, the absence will be unexcused. Excused absences will involve make-up assignments, with make-up assignment procedures to be discussed in class on the first day.~~ 

If you are unable to complete an assignment due to a personal and/or family emergency, you should contact your instructor or discussion leader as soon as possible. On a case-by-case basis, the instructor will determine whether the emergency qualifies as an excused absence. 

# Expected Classroom Behavior
Students are expected to participate in classroom activities. If use of digital devices or engagement in other non-class activities during class for purposes not regarding classroom activities is critically necessary, the student should engage in these activities while on break, or check with the instructor to arrange for a 10-minute break for unusual circumstances, but only if critically necessary. 

# Course Policies 
## Diversity, Equity and Inclusion
It is the policy of the University of Oregon to support and value equity and diversity and to provide inclusive learning environments for all students.  To do so requires that we: 

* respect the dignity and essential worth of all individuals. 
* promote a culture of respect throughout the University community. 
* respect the privacy, property, and freedom of others. 
* reject bigotry, discrimination, violence, or intimidation of any kind. 
* practice personal and academic integrity and expect it from others. 
* promote the diversity of opinions, ideas and backgrounds which is the lifeblood of the university.

In this course, class discussions, projects/activities and assignments will challenge students to think critically about and be sensitive to the influence, and intersections, of race, ethnicity, nationality, documentation status, language, religion, gender, socioeconomic background, physical and cognitive ability, sexual orientation, and other cultural identities and experiences. Students will be encouraged to develop or expand their respect and understanding of such differences.

Maintaining an inclusive classroom environment where all students feel able to talk about their cultural identities and experiences, ideas, beliefs, and values will not only be my responsibility, but the responsibility of each class member as well. Behavior that disregards or diminishes another student will not be permitted for any reason. This means that no racist, ableist, transphobic, xenophobic, chauvinistic or otherwise derogatory comments will be allowed. It also means that students must pay attention and listen respectfully to each other’s comments.

## Indigenous Recognition Statement
The University of Oregon is located on Kalapuya Ilihi, the traditional indigenous homeland of the Kalapuya people. Today, descendants are citizens of the Confederated Tribes of the Grand Ronde Community of Oregon and the Confederated Tribes of the Siletz Indians of Oregon, and they continue to make important contributions in their communities, at UO, and across the land we now refer to as Oregon.

## Using Pronouns and Personal Preference
The College of Education is always working to include and engage everyone. One way we can do this is to share our pronouns, or the words we want to be called when people aren’t using our name. Like names, pronouns are an important part of how we identify ourselves. Because we recognize that assuming someone’s gender can be hurtful, especially to members of our community who are transgender, genderqueer, or non-binary. This practice can assist in promoting respectful communication. As a community, we are all learning together about the importance of pronouns and being better allies to the trans community on campus. If you would like to ensure clarity around pronouns, please feel free to share any pronouns you would prefer me to use when referring to you to help me be aware of how to address you respectfully. Please visit this university website for more information. https://studentlife.uoregon.edu/pronouns

## Children in class

I applaud all of you who go to graduate school with children! I had both of my girls while a doctoral student, and I understand the difficulty in balancing academic, work, and family commitments. I want you to succeed. Here are my policies regarding children in class:

1. All breastfeeding babies are welcome in class as often as necessary.
2. Non-nursing babies and older children are welcome whenever alternate arrangements cannot be made. As a parent of two young children, I understand that babysitters fall through, partners have conflicting schedules, children get sick, and other issues arise that leave parents with few other options.
3. In cases where children come to class, I invite parents/caregivers to sit close to the door so as to more easily excuse yourself to attend to your child's needs. Non-parents in the class: please reserve seats near the door for your parenting classmates.
4. All students are expected to join with me in creating a welcoming environment that is respectful of your classmates who bring children to class.

I understand that sleep deprivation and exhaustion are among the most difficult aspects of parenting young children. The struggle of balancing school, work, childcare, and graduate school is tiring, and I will do my best to accommodate any such issues while maintaining the same high expectations for all students enrolled in the class. ***Please do not hesitate to contact me with any questions or concerns.***


## Documented Disability
Appropriate accommodations will be provided for students with documented disabilities. If you have a documented disability and require accommodation, arrange to meet with the course instructor within the first two weeks of the term. The documentation of your disability must come in writing from the Accessible Education Center in the Office of Academic Advising and Student Services.  Disabilities may include (but are not limited to) neurological impairment, orthopedic impairment, traumatic brain injury, visual impairment, chronic medical conditions, emotional/psychological disabilities, hearing impairment, and learning disabilities. For more information on Accessible Education Center, please see http://aec.uoregon.edu 

## Mandatory Reporting of Child Abuse
UO employees, including faculty, staff, and GEs, are mandatory reporters of child abuse. This statement is to advise you that that your disclosure of information about child abuse to a UO employee may trigger the UO employee’s duty to report that information to the designated authorities. Please refer to the following links for detailed information about mandatory reporting:
http://hr.uoregon.edu/policies-leaves/general-information/mandatory-reporting-child-abuse-and-neglect

## Reporting Title IX Experiences
Any student who has experienced sexual assault, relationship violence, sex or gender-based bullying, stalking, and/or sexual harassment may seek resources and help at safe.uoregon.edu. To get help by phone, a student can also call either the UO’s 24-hour hotline at 541-346-7244 [SAFE], or the non-confidential Title IX Coordinator at 541-346-8136. From the SAFE website, students may also connect to Callisto, a confidential, third-party reporting site that is not a part of the university. 

Students experiencing any other form of prohibited discrimination or harassment can find information at aaeo.uoregon.edu or contact the non-confidential AAEO office at 541-346-3123 or the Dean of Students Office at 541-346-3216 for help. As UO policy has different reporting requirements based on the nature of the reported harassment or discrimination, additional information about reporting requirements for discrimination or harassment unrelated to sexual assault, relationship violence, sex or gender based bullying, stalking, and/or sexual harassment is available at http://aaeo.uoregon.edu/content/discrimination-harassment 

Specific details about confidentiality of information and reporting obligations of employees can be found at https://titleix.uoregon.edu. 

## Instructor Reporting Status
The instructor of this class will direct students who disclose sexual harassment or sexual violence to resources that can help and has the responsibility to report the information shared with them to the university administration. The instructor of this class is required to report all other forms of prohibited discrimination or harassment to the university administration.

## Academic Misconduct Policy
All students are subject to the regulations stipulated in the UO Student Conduct Code (http://conduct.uoregon.edu). This code represents a compilation of important regulations, policies, and procedures pertaining to student life. It is intended to inform students of their rights and responsibilities during their association with this institution, and to provide general guidance for enforcing those regulations and policies essential to the educational and research missions of the University.  

## Conflict Resolution 
Several options, both informal and formal, are available to resolve conflicts for students who believe they have been subjected to or have witnessed bias, unfairness, or other improper treatment. 

It is important to exhaust the administrative remedies available to you including discussing the conflict with the specific individual, contacting the Department Head, or within the College of Education, you can contact the Associate Dean for Academic Affairs and Equity (Lillian Duran, 541-346-2502, lduran@uoregon.edu). Outside the College, you can contact: 

* UO Bias Response Team: 346-3216 http://bias.uoregon.edu/whatbrt.htm 
* Conflict Resolution Services 346-3216 http://studentlife.uoregon.edu/support
* Affirmative Action and Equal Opportunity: 346-3123 http://aaeo.uoregon.edu/

## Grievance Policy
A student or group of students of the College of Education may appeal decisions or actions pertaining to admissions, programs, evaluation of performance and program retention and completion. Students who decide to file a grievance should follow the student grievance procedure (https://policies.uoregon.edu/grievance-procedures) and/or consult with the College Associate Dean for Academic Affairs (Lillian Duran, 346-2502, lduran@uoregon.edu).

## In Case of Inclement Weather 
In the event the University operates on a curtailed schedule or closes, UO media relations will notify the Eugene-Springfield area radio and television stations as quickly as possible. In addition, a notice regarding the university’s schedule will be posted on the UO main home page (in the “News” section) at http://www.uoregon.edu. Additional information is available at http://hr.uoregon.edu/policy/weather.html.

If an individual class must be canceled due to inclement weather, illness, or other reason, a notice will be posted on Canvas or via email. During periods of inclement weather, please check Canvas and your email rather than contact department personnel. Due to unsafe travel conditions, departmental staff may be limited and unable to handle the volume of calls from you and others.

## Course Incomplete Policy
Students are expected to be familiar with university policy regarding grades of “incomplete” and the time line for completion. For details on the policy and procedures regarding incompletes, Please see: https://education.uoregon.edu/academics/incompletes-courses
